<a href="https://colab.research.google.com/github/Fahreza2626/TugasKelompokPakArifin/blob/main/EDA_2_DynandFz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## LATIHAN 1

In [ ]:
import numpy as np

harga = np.array([5000, 7000, 3000, 12000, 4500])
print('Rata-rata harga:', harga.mean())
print('Harga tertinggi:', harga.max())
print('Harga setelah diskon 10%:', harga * 0.9)

Rata-rata harga: 6300.0
Harga tertinggi: 12000
Harga setelah diskon 10%: [ 4500.  6300.  2700. 10800.  4050.]

**JAWABAN:**

Jika menggunakan list Python biasa, kode tersebut akan menghasilkan pesan error (TypeError). Python bawaan tidak bisa mengalikan list dengan bilangan desimal (float). Di Python standar, perkalian pada list hanya berfungsi dengan bilangan bulat (integer) untuk menggandakan/mengulang isi list (misal: [1, 2] * 2 menjadi [1, 2, 1, 2]). Sebaliknya, NumPy array memiliki fitur vectorization, yang memungkinkan operasi matematika diterapkan secara langsung ke setiap angka di dalam array tersebut sekaligus.

## LATIHAN 2

In [ ]:
import pandas as pd
# Mengimpor library Pandas dan disingkat menjadi pd

data_kantin = {
# Membuat variabel untuk menyimpan data kantin

    'menu': ['Nasi Goreng', 'Es Teh', 'Mie Ayam', 'Es Teh', None],
    # Membuat kolom menu dan None berarti data kosong

    'harga': [12000, 4000, 10000, 4000, 8000],
    # Membuat kolom harga untuk setiap menu

    'terjual': [23, 40, None, 35, 18]
    # Membuat kolom jumlah barang yang terjual
    # None berarti terdapat data yang kosong

}

df = pd.DataFrame(data_kantin)
# Mengubah data_kantin menjadi DataFrame Pandas

print(df)
# Menampilkan seluruh DataFrame ke layar

     tanggal         menu kategori  harga  terjual  pendapatan
0 2026-08-20   Teh Hangat  Minuman   3000       11       33000
1 2026-08-31  Nasi Goreng  Makanan  12000       29      348000
2 2026-08-21  Nasi Goreng  Makanan  12000       28      336000
3 2026-08-28   Teh Hangat  Minuman   3000       12       36000
4 2026-08-21     Es Jeruk  Minuman   5000       19       95000
<class 'pandas.core.frame.DataFrame'>
Index: 105 entries, 0 to 109
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   tanggal     105 non-null    datetime64[ns]
 1   menu        105 non-null    object
 2   kategori    105 non-null    object
 3   harga       105 non-null    int64
 4   terjual     105 non-null    int64
 5   pendapatan  105 non-null    int64
dtypes: datetime64[ns](1), int64(3), object(2)
memory usage: 5.7+ KB
None
                   tanggal         harga     terjual     pendapatan
count                  105    105.000000  105.000000     105.000000
mean   2026-08-26 00:00:00   6285.714286   23.161905  134333.333333
min    2026-08-17 00:00:00   2000.000000    8.000000   30000.000000
25%    2026-08-20 00:00:00   3000.000000   13.000000   72000.000000
50%    2026-08-26 00:00:00   5000.000000   21.000000  105000.000000
75%    2026-09-01 00:00:00  10000.000000   33.000000  170000.000000
max    2026-09-04 00:00:00  12000.000000   45.000000  396000.000000
std                    NaN   3510.189250   10.885880   87252.580595
(105, 6)
Index(['tanggal', 'menu', 'kategori', 'harga', 'terjual', 'pendapatan'], dtype='object')
tanggal       0
menu          0
kategori      0
harga         0
terjual       0
pendapatan    0
dtype: int64

**JAWABAN:**

Berdasarkan kode di modul, kolom yang memiliki data kosong (bernila None) adalah kolom menu dan terjual.

## LATIHAN 3

In [ ]:
import pandas as pd

df = pd.read_csv('data_kantin.csv')

df.head()

      tanggal         menu kategori  harga  terjual
0  2026-08-20   Teh Hangat  Minuman   3000     11.0
1  2026-08-31  Nasi Goreng  Makanan  12000     29.0
2  2026-08-21  Nasi Goreng  Makanan  12000     28.0
3  2026-08-28   Teh Hangat  Minuman   3000     12.0
4  2026-08-21     Es Jeruk  Minuman   5000     19.0

**JAWABAN:**

Kolom menu dan terjual akan memiliki angka non-null (data yang tidak kosong) lebih sedikit dari total baris. Artinya, di dalam kolom-kolom tersebut terdapat sel yang datanya hilang, kosong, atau tidak terisi (missing value).

## LATIHAN 4

In [ ]:
import pandas as pd

df = pd.read_csv('data_kantin.csv')

print(df.isnull().sum())
df['terjual'] = df['terjual'].fillna(0) # isi kekosongan dengan 0
df = df.dropna(subset=['menu']) # hapus baris jika kolom menu kosong

tanggal     0
menu        3
kategori    0
harga       0
terjual     6
dtype: int64

Ini adalah bagian dari logika pembersihan data (Data Cleaning):  

- Kolom terjual (Numerik): Jika jumlah terjual kosong, sangat logis untuk berasumsi bahwa pada saat itu barang tersebut tidak laku sama sekali, jadi masuk akal jika kita menggantinya dengan angka 0.
- Kolom menu (Kategorikal): Jika nama menu kosong, data tersebut kehilangan identitasnya. Kita tidak bisa menebak menu apa itu, dan baris data tanpa nama barang menjadi tidak berguna untuk dianalisis lebih lanjut (tidak bisa dikelompokkan). Oleh karena itu, baris tersebut lebih baik dibuang (drop).

## LATIHAN 5

In [ ]:
print(df.duplicated().sum()) # jumlah baris duplikat
df = df.drop_duplicates()

df['harga'] = df['harga'].astype(int) # memastikan tipe data harga adalah integer
print(df.dtypes)

5
tanggal      object
menu         object
kategori     object
harga         int64
terjual     float64
dtype: object

**JAWABAN:**

Memastikan tipe data benar sangat krusial karena komputer memproses data sesuai tipenya. Jika kolom harga secara tidak sengaja terbaca sebagai teks (string / object) alih-alih angka (integer), kamu tidak akan bisa menjumlahkan, mengalikan, atau mencari rata-ratanya. Fungsi astype(int) memastikan data tersebut diakui sebagai angka valid. Mengenai jumlah baris setelah drop_duplicates(), baris hanya akan berkurang jika ada dua baris (atau lebih) yang datanya sama persis dari ujung ke ujung.

## LATIHAN 6

In [ ]:
import pandas as pd

df = pd.read_csv('data_kantin.csv')

laris = df[df['terjual'] > 20]
urut = df.sort_values(by='terjual', ascending=False) # filtering

# sorting
df['total_pendapatan'] = df['harga'] * df['terjual'] # kolom turunan

ringkasan = df.groupby('menu')['total_pendapatan'].sum() # agregasi
print(ringkasan)

menu
Es Jeruk       1560000.0
Es Teh         2144000.0
Kerupuk        1042000.0
Mie Ayam       2570000.0
Nasi Goreng    4188000.0
Roti Bakar     1368000.0
Teh Hangat      459000.0
Name: total_pendapatan, dtype: float64


**JAWABAN:**

- Nasi Goreng: 12.000 * 23 = 276.000
- Es Teh: (4.000 * 40) + (4.000 * 35) = 300.000
- Mie Ayam: 10.000 * 0 (karena nilai kosong diganti 0) = 0
- Menu tertinggi adalah Es Teh (Rp 300.000).

Pengambilan Keputusan: Informasi ini membuktikan bahwa Es Teh adalah penyumbang pendapatan terbesar (produk paling laris). Kantin bisa mengambil keputusan untuk memperbanyak stok bahan pembuat Es Teh setiap harinya agar tidak kehabisan, atau membuat paket promo bundling (misal: Nasi Goreng + Es Teh) untuk mendongkrak penjualan makanan.

## KERJA KELOMPOK - DATA LOADING

In [ ]:
import pandas as pd
df = pd.read_csv("data_kantin.csv")
print("Dataset berhasil dimuat.")

Dataset berhasil dimuat.

## KERJA KELOMPOK - DATA INSPECTION

In [ ]:
print("=== 5 DATA PERTAMA ===")
display(df.head())

print("\n=== INFORMASI DATASET ===")
df.info()

print("\n=== STATISTIK DESKRIPTIF ===")
display(df.describe())

print("\n=== UKURAN DATASET ===")
print("Jumlah baris dan kolom:", df.shape)

=== 5 DATA PERTAMA ===

      tanggal         menu kategori  harga  terjual
0  2026-08-20   Teh Hangat  Minuman   3000     11.0
1  2026-08-31  Nasi Goreng  Makanan  12000     29.0
2  2026-08-21  Nasi Goreng  Makanan  12000     28.0
3  2026-08-28   Teh Hangat  Minuman   3000     12.0
4  2026-08-21     Es Jeruk  Minuman   5000     19.0

=== INFORMASI DATASET ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   110 non-null    object
 1   menu      107 non-null    object
 2   kategori  110 non-null    object
 3   harga     110 non-null    int64
 4   terjual   104 non-null    float64
dtypes: float64(1), int64(1), object(3)
memory usage: 4.4+ KB

=== STATISTIK DESKRIPTIF ===

              harga     terjual
count    110.000000  104.000000
mean    6336.363636   22.923077
std     3520.001232   10.831178
min     2000.000000    8.000000
25%     3000.000000   13.000000
50%     5000.000000   20.000000
75%    10000.000000   33.000000
max    12000.000000   45.000000

=== UKURAN DATASET ===
Jumlah baris dan kolom: (110, 5)

## KERJA KELOMPOK - MENGECEK KUALITAS DATA

In [ ]:
print("=== MISSING VALUE ===")
print(df.isnull().sum())

print("\n=== DATA DUPLIKAT ===")
print("Jumlah data duplikat:", df.duplicated().sum())

print("\n=== TIPE DATA ===")
print(df.dtypes)

=== MISSING VALUE ===
tanggal     0
menu        3
kategori    0
harga       0
terjual     6
dtype: int64

=== DATA DUPLIKAT ===
Jumlah data duplikat: 5

=== TIPE DATA ===
tanggal      object
menu         object
kategori     object
harga         int64
terjual     float64
dtype: object

## KERJA KELOMPOK - MENGUBAH TIPE TANGGAL DATA

In [ ]:
df["tanggal"] = pd.to_datetime(df["tanggal"], errors="coerce")

print(df.dtypes)

tanggal     datetime64[ns]
menu                object
kategori            object
harga                int64
terjual            float64
dtype: object

**JAWABAN :**

Kolom tanggal diubah menjadi tipe datetime agar dapat digunakan untuk analisis berdasarkan tanggal dan pengurutan data.

## KERJA KELOMPOK - MENGHAPUS DATA DUPLIKAT

In [ ]:
print("Jumlah data sebelum:", len(df))

df = df.drop_duplicates()

print("Jumlah data setelah:", len(df))
print("Duplikat yang dihapus:", 110 - len(df))

Jumlah data sebelum: 110
Jumlah data setelah: 105
Duplikat yang dihapus: 5

**JAWABAN :**

Data duplikat dihapus karena merupakan data yang sama dan dapat menyebabkan hasil perhitungan penjualan menjadi lebih besar dari kondisi sebenarnya.

## KERJA KELOMPOK - MENANGANI MISSING VALUE PADA MENU

In [ ]:
df.loc[
    df["menu"].isna() &
    (df["harga"] == 12000) &
    (df["kategori"] == "Makanan"),
    "menu"
] = "Nasi Goreng"

df.loc[
    df["menu"].isna() &
    (df["harga"] == 3000) &
    (df["kategori"] == "Minuman"),
    "menu"
] = "Teh Hangat"

df.loc[
    df["menu"].isna() &
    (df["harga"] == 4000) &
    (df["kategori"] == "Minuman"),
    "menu"
] = "Es Teh"

print("Missing value pada menu:", df["menu"].isna().sum())

Missing value pada menu: 0

**JAWABAN :**

Missing value pada menu tidak langsung dihapus karena nama menu masih dapat ditentukan berdasarkan kombinasi harga dan kategori.

## KERJA KELOMPOK - MENANGANI MISSING VALUE TERJUAL

In [ ]:
median_menu = df.groupby("menu")["terjual"].median()

print("Median terjual setiap menu:")
display(median_menu)

df["terjual"] = df["terjual"].fillna(
    df["menu"].map(median_menu)
)

print("\nJumlah missing value terjual setelah cleaning:")
print(df["terjual"].isna().sum())

Median terjual setiap menu:

menu
Es Jeruk       21.0
Es Teh         41.0
Kerupuk        34.5
Mie Ayam       17.0
Nasi Goreng    25.5
Roti Bakar     11.0
Teh Hangat     12.0
Name: terjual, dtype: float64

Jumlah missing value terjual setelah cleaning:
0

**JAWABAN :**

Median berdasarkan menu digunakan karena jumlah penjualan tiap menu berbeda. Cara ini lebih sesuai daripada menggunakan satu median untuk seluruh dataset.

## KERJA KELOMPOK - MEMASTIKAN TIPE DATA SUDAH SESUAI

In [ ]:
df["terjual"] = df["terjual"].round().astype(int)

print("=== TIPE DATA SETELAH CLEANING ===")
df.info()

print("\n=== MISSING VALUE SETELAH CLEANING ===")
print(df.isnull().sum())

print("\n=== DUPLIKAT SETELAH CLEANING ===")
print("Jumlah duplikat:", df.duplicated().sum())

=== TIPE DATA SETELAH CLEANING ===
<class 'pandas.core.frame.DataFrame'>
Index: 105 entries, 0 to 109
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   105 non-null    datetime64[ns]
 1   menu      105 non-null    object
 2   kategori  105 non-null    object
 3   harga     105 non-null    int64
 4   terjual   105 non-null    int64
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 4.9+ KB

=== MISSING VALUE SETELAH CLEANING ===
tanggal     0
menu        0
kategori    0
harga       0
terjual     0
dtype: int64

=== DUPLIKAT SETELAH CLEANING ===
Jumlah duplikat: 0

##KERJA KELOMPOK - FILTERING

In [ ]:
df_filter = df[df["terjual"] >= 20]

print("Data penjualan dengan jumlah terjual >= 20:")
display(df_filter)

Data penjualan dengan jumlah terjual >= 20:

       tanggal         menu kategori  harga  terjual
1   2026-08-31  Nasi Goreng  Makanan  12000       29
2   2026-08-21  Nasi Goreng  Makanan  12000       28
5   2026-08-27     Es Jeruk  Minuman   5000       21
7   2026-08-17       Es Teh  Minuman   4000       41
8   2026-08-25      Kerupuk    Snack   2000       32
9   2026-09-01  Nasi Goreng  Makanan  12000       20
12  2026-08-17  Nasi Goreng  Makanan  12000       23
15  2026-08-31     Es Jeruk  Minuman   5000       20
16  2026-09-01       Es Teh  Minuman   4000       45
17  2026-09-02     Es Jeruk  Minuman   5000       21
18  2026-08-25     Es Jeruk  Minuman   5000       20
20  2026-09-02  Nasi Goreng  Makanan  12000       33
22  2026-08-24     Es Jeruk  Minuman   5000       23
23  2026-09-01     Mie Ayam  Makanan  10000       20
26  2026-08-19       Es Teh  Minuman   4000       45
31  2026-08-17      Kerupuk    Snack   2000       35
32  2026-08-28  Nasi Goreng  Makanan  12000       27
34  2026-08-31       Es Teh  Minuman   4000       38
38  2026-08-24  Nasi Goreng  Makanan  12000       22
39  2026-08-27       Es Teh  Minuman   4000       43
44  2026-09-04      Kerupuk    Snack   2000       36
46  2026-08-26     Es Jeruk  Minuman   5000       22
47  2026-08-26  Nasi Goreng  Makanan  12000       31
50  2026-09-03     Es Jeruk  Minuman   5000       20
54  2026-08-20      Kerupuk    Snack   2000       34
56  2026-08-27  Nasi Goreng  Makanan  12000       24
57  2026-09-01      Kerupuk    Snack   2000       38
58  2026-08-21       Es Teh  Minuman   4000       39
59  2026-09-03  Nasi Goreng  Makanan  12000       25
62  2026-08-20  Nasi Goreng  Makanan  12000       26
63  2026-08-19     Mie Ayam  Makanan  10000       20
66  2026-08-25  Nasi Goreng  Makanan  12000       26
68  2026-08-24      Kerupuk    Snack   2000       34
69  2026-08-18      Kerupuk    Snack   2000       33
70  2026-08-28       Es Teh  Minuman   4000       42
71  2026-08-24       Es Teh  Minuman   4000       41
72  2026-08-27      Kerupuk    Snack   2000       34
73  2026-08-18       Es Teh  Minuman   4000       38
75  2026-08-18     Es Jeruk  Minuman   5000       22
77  2026-08-31      Kerupuk    Snack   2000       35
79  2026-09-03       Es Teh  Minuman   4000       40
80  2026-08-20       Es Teh  Minuman   4000       42
81  2026-08-21      Kerupuk    Snack   2000       36
82  2026-09-02       Es Teh  Minuman   4000       41
85  2026-09-03      Kerupuk    Snack   2000       33
86  2026-09-04       Es Teh  Minuman   4000       39
87  2026-08-20     Es Jeruk  Minuman   5000       21
91  2026-08-26      Kerupuk    Snack   2000       36
92  2026-08-18  Nasi Goreng  Makanan  12000       25
93  2026-08-26       Es Teh  Minuman   4000       40
96  2026-08-27     Mie Ayam  Makanan  10000       21
98  2026-08-28      Kerupuk    Snack   2000       33
99  2026-09-04     Es Jeruk  Minuman   5000       22
104 2026-08-17     Es Jeruk  Minuman   5000       21
105 2026-09-01     Es Jeruk  Minuman   5000       24
106 2026-09-04  Nasi Goreng  Makanan  12000       28
107 2026-08-19      Kerupuk    Snack   2000       37
108 2026-08-25       Es Teh  Minuman   4000       44
109 2026-09-02      Kerupuk    Snack   2000       34

##KERJA KELOMPOK - SORTING

In [ ]:
df_sort = df.sort_values(
    by="terjual",
    ascending=False
)

print("10 penjualan tertinggi:")
display(
    df_sort[[
        "tanggal",
        "menu",
        "kategori",
        "harga",
        "terjual"
    ]].head(10)
)

10 penjualan tertinggi:

       tanggal    menu kategori  harga  terjual
16  2026-09-01  Es Teh  Minuman   4000       45
26  2026-08-19  Es Teh  Minuman   4000       45
108 2026-08-25  Es Teh  Minuman   4000       44
39  2026-08-27  Es Teh  Minuman   4000       43
70  2026-08-28  Es Teh  Minuman   4000       42
80  2026-08-20  Es Teh  Minuman   4000       42
71  2026-08-24  Es Teh  Minuman   4000       41
7   2026-08-17  Es Teh  Minuman   4000       41
82  2026-09-02  Es Teh  Minuman   4000       41
79  2026-09-03  Es Teh  Minuman   4000       40

##KERJA KELOMPOK - MEMBUAT KOLOM TURUNAN

In [ ]:
df["pendapatan"] = df["harga"] * df["terjual"]

print("Data dengan kolom pendapatan:")
display(df.head())

Data dengan kolom pendapatan:

     tanggal         menu kategori  harga  terjual  pendapatan
0 2026-08-20   Teh Hangat  Minuman   3000       11       33000
1 2026-08-31  Nasi Goreng  Makanan  12000       29      348000
2 2026-08-21  Nasi Goreng  Makanan  12000       28      336000
3 2026-08-28   Teh Hangat  Minuman   3000       12       36000
4 2026-08-21     Es Jeruk  Minuman   5000       19       95000

##KERJA KELOMPOK - GROUPY / AGREGASI

In [ ]:
analisis_menu = df.groupby("menu").agg(
    total_terjual=("terjual", "sum"),
    total_pendapatan=("pendapatan", "sum"),
    rata_rata_terjual=("terjual", "mean")
).sort_values(
    by="total_pendapatan",
    ascending=False
)

print("Analisis penjualan berdasarkan menu:")
display(analisis_menu)

Analisis penjualan berdasarkan menu:

             total_terjual  total_pendapatan  rata_rata_terjual
menu
Nasi Goreng            386           4632000          25.733333
Mie Ayam               258           2580000          17.200000
Es Teh                 618           2472000          41.200000
Es Jeruk               313           1565000          20.866667
Roti Bakar             161           1288000          10.733333
Kerupuk                520           1040000          34.666667
Teh Hangat             176            528000          11.733333